HEADER_REGEX = r"^([A-Z]{2})(\d{2})(\d{4})"
HEADER_ID_COL = 0
HEADER_NAME_COL = 1
HEADER_COUNT_COL = 2

DATA_DATE_COL = 0
DATA_TIME_COL = 1
DATA_RECORD_ID_COL = 2
DATA_SYSTEM_STATUS_COL = 3
DATA_LAT_COL = 4
DATA_LON_COL = 5
DATA_MAX_WIND_COL = 6
